version: '3.8'

services:
  users-db:
    image: postgres:15
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    ports:
      - "5434:5432"  
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      retries: 5
      timeout: 5s

  user-service:
    build: ./user-service
    container_name: users_service
    restart: always
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgresql://admin:admin@users-db:5432/users_db"
    depends_on:
      users-db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - users-db

volumes:
  users_postgres_data:
    driver: local
  pgadmin_data:
    driver: local
